### PR TITLE
Support `&dyn VariableMap`

### PR DESCRIPTION
**Pull request by andylizi**
This should be a backward-compatible change.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Thanks for the PR. Changes look good!

I think it would be good to add some tests that use a `&dyn VariableMap` to ensure it doesn't break in the future.

Do you want to do that or shall I?

**Comment by de-vri-es** [comment]
I want to release it, so I added a test :)

**Comment by de-vri-es** [comment]
Released as `0.2.3` :tada: 

Thanks again!

**Comment by andylizi** [comment]
Thank you for the great work! 🎉

**Pull request merged**
